#pragma once

#include <QtCore/qglobal.h>

#if defined(WEBSOCKET_LIBRARY)
#  define WEBSOCKET_EXPORT Q_DECL_EXPORT
#else
#  define WEBSOCKET_EXPORT Q_DECL_IMPORT
#endif


#ifdef WEBSOCKET_NAMESPACE

# define WEBSOCKET_PREPEND_NAMESPACE(name) ::WEBSOCKET_NAMESPACE::name
# define WEBSOCKET_USE_NAMESPACE using namespace ::WEBSOCKET_NAMESPACE;
# define WEBSOCKET_BEGIN_NAMESPACE namespace WEBSOCKET_NAMESPACE {
# define WEBSOCKET_END_NAMESPACE }
# define WEBSOCKET_FORWARD_DECLARE_CLASS(name) \
    WEBSOCKET_BEGIN_NAMESPACE class name; WEBSOCKET_END_NAMESPACE \
    using WEBSOCKET_PREPEND_NAMESPACE(name);

#else

# define WEBSOCKET_PREPEND_NAMESPACE(name) ::name
# define WEBSOCKET_USE_NAMESPACE
# define WEBSOCKET_BEGIN_NAMESPACE
# define WEBSOCKET_END_NAMESPACE
# define WEBSOCKET_FORWARD_DECLARE_CLASS(name) class name;

#endif // WEBSOCKET_NAMESPACE
